# ------------------
# 项目信息
# ------------------
site_name: "Note_Share" # 必需：您的网站标题
site_url: "https://example.com/" # 部署后的网站URL
site_author: "wuuixm"
site_description: "这里是关于我的项目的详细文档。"

# ------------------
# 仓库信息
# ------------------
repo_url: "https://github.com/wuuixm/Note_repository" # 您的代码仓库URL
repo_name: "wuuixm/Note_repository" # 显示的仓库名称
edit_uri: "edit/main/docs/" # “编辑此页”的链接路径，需根据分支和文档目录调整

# ------------------
# 版权信息
# ------------------
copyright: "Copyright &copy; 2025 WUUIXM"

# ------------------
# 主题配置 (使用 Material for MkDocs)
# ------------------
theme:
  name: material
  language: "zh" # 设置语言为中文
  favicon: assests/open-book.ico # 浏览器标签页的小图标路径
  palette:
    # 日间模式
    - scheme: default
      primary: "indigo" # 主色调（影响标题栏、按钮等）
      accent: "indigo" # 强调色（链接、选中状态等）
      toggle:
        icon: material/brightness-7
        name: 切换到夜间模式
    # 夜间模式
    - scheme: slate
      primary: "black"
      accent: "indigo"
      toggle:
        icon: material/brightness-4
        name: 切换到日间模式
  features:
    #- toc.integrate # 
    - navigation.instant # 单页应用式导航（页面无需刷新）
    - navigation.tracking # 自动高亮当前页面导航
    #- navigation.tabs # 使用顶部标签页作为导航
    - navigation.sections # 左侧导航栏自动展开当前分区
    - navigation.top # 返回顶部的按钮
    - search.suggest # 搜索建议
    - search.highlight # 搜索结果高亮
    - content.code.copy # 代码块一键复制按钮
    - content.code.annotate # 代码块注释功能
    # - navigation.footer # 在页面底部显示导航链接
    # - content.tabs.link # 选项卡式内容切换
    # - navigation.expand # 默认展开所有导航项
    # - navigation.indexes # 支持目录索引页
    # - toc.integrate # 将目录集成到侧边栏（而不是单独显示）

  # 自定义字体
  font:
    text: Roboto # 正文字体
    code: Roboto Mono # 代码字体
    # text: Noto Serif SC # 中文字体（适合中文文档）
    # code: Source Code Pro # 代码字体备选

  # 自定义标题栏颜色（通过CSS变量覆盖）
  # custom_dir: overrides # 自定义主题文件目录（需创建 overrides/main.html）
  # 例如，在 overrides/main.html 中可以添加：
  # <style>
  #   :root {
  #     --md-primary-fg-color: #3f51b5; /* 自定义标题栏前景色 */
  #     --md-primary-bg-color: #ffffff; /* 自定义标题栏背景色 */
  #     --md-accent-fg-color: #ff4081; /* 自定义强调色 */
  #   }
  # </style>

  # 图标配置
  icon:
     repo: fontawesome/brands/github # 仓库图标（支持 FontAwesome 或 Material 图标）
    # logo: material/library # 自定义Logo图标（如果不使用图片）
    # admonition: # 自定义提示框图标
    #   note: material/note
    #   warning: material/alert
    #   tip: material/lightbulb

# ------------------
# 导航菜单
# ------------------
# 如果不配置nav，MkDocs会根据docs目录结构自动生成
# nav:
#   - '首页': 'index.md'
#   - '用户指南':
#     - '安装教程': 'guides/installation.md'
#     - '快速上手': 'guides/getting-started.md'
#   - 'API参考':
#     - '模块A': 'reference/module-a.md'
#     - '模块B': 'reference/module-b.md'
#   - '关于': 'about.md'
nav:
  - '首页': 'index.md'
  - 'Python虚拟环境uv使用教程': 'UV.md'
  - 'Github Desktop使用教程': 'Github Desktop.md'

# ------------------
# Markdown 扩展
# ------------------
markdown_extensions:
  - toc:
      permalink: true # 为标题生成永久链接
      toc_depth: 3 # 目录深度（1-6）
  - admonition # 美观的提示框 (note, warning, tip等)
  - pymdownx.details # 可折叠的内容块
  - pymdownx.superfences: # 更强大的代码块功能
      custom_fences: # 自定义代码块类型
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic # 标记和高亮修改建议
  - pymdownx.caret # ^^插入^^ 和 ~~删除~~ 语法
  - pymdownx.keys # ++Kbd++ 样式的按键显示
  - pymdownx.mark # ==高亮== 文本
  - pymdownx.tilde # ~~删除线~~
  - attr_list # 为Markdown元素添加HTML属性
  - md_in_html # 允许在HTML块中使用Markdown
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight: # 代码高亮
      anchor_linenums: true
      line_spans: __span # 为代码行添加span标签
      # use_pygments: true # 使用Pygments高亮（默认）
      # auto_title: true # 自动为代码块添加语言标题
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed: # 选项卡内容
      alternate_style: true
  # - pymdownx.arithmatex: # 支持数学公式（LaTeX）
  #     tex_inline_wrap: ['$', '$'] # 内联公式分隔符
  #     tex_block_wrap: ['$$', '$$'] # 块公式分隔符
  # - pymdownx.tasklist: # 任务列表（checkbox）
  #     custom_checkbox: true
  # - pymdownx.magiclink # 自动将URL和邮箱转为可点击链接
  # - pymdownx.betterem # 改进的强调语法（加粗、斜体等）
  # - def_list # 支持定义列表
  # - footnotes # 支持脚注

# ------------------
# 额外插件
# ------------------
plugins:
  - search: # 内置搜索插件，Material主题已默认集成并强化
      lang: zh # 搜索支持中文
      # prebuild_index: true # 预构建搜索索引以提高速度（需要更多构建时间）
  # - minify: # 压缩HTML、CSS和JS输出
  #     minify_html: true
  #     minify_css: true
  #     minify_js: true
  # - git-revision-date-localized: # 显示页面的最后更新时间
  #     type: date
  #     enable_creation_date: true
  # - awesome-pages: # 增强页面导航控制
  #     filename: .pages
  # - mkdocs-git-authors: # 显示页面作者（需要Git支持）
  # - mkdocs-simple-hooks: # 自定义构建钩子
  #     hooks:
  #       on_pre_build: "my_hooks.pre_build"
  #       on_post_build: "my_hooks.post_build"
  # - social: # 添加社交卡片（用于SEO和分享）
  #     cards: true
  #     cards_layout: default
  # - mkdocstrings: # 自动生成代码文档（适合Python项目）
  #     handlers:
  #       python:
  #         options:
  #           docstring_style: google
  #           merge_init_into_class: true

# ------------------
# 额外CSS和JS
# ------------------
extra_css:
   - css/custom.css # 自定义CSS文件路径
# extra_javascript:
#   - js/extra.js # 自定义JS文件路径
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js # 加载MathJax以支持数学公式

# ------------------
# 其他配置
# ------------------
# strict: true # 严格模式，检查无效链接
# dev_addr: '0.0.0.0:8000' # 开发服务器地址和端口
# use_directory_urls: true # 使用目录式URL（例如 /page/ 而不是 /page.html）
# extra:
#   analytics: # 配置分析工具
#     provider: google
#     property: UA-XXXXXXXXX-X # Google Analytics ID
#   social: # 社交媒体链接
#     - icon: fontawesome/brands/github
#       link: https://github.com/your-username
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/your-username
#   version: # 版本选择器
#     provider: mike
#     default: latest